site_name: AIAgents4Pharma

nav:
  - Home: index.md

  - Talk2Biomodels:
      - Introduction: talk2biomodels/intro.md
      - FAQ: talk2biomodels/faq.md
      - Tutorials: ./notebooks/talk2biomodels/tutorial.ipynb
      - Case Studies:
        - Precision medicine: talk2biomodels/cases/Case_1.md
        - Epidemiology: talk2biomodels/cases/Case_2.md
        - Emergent system properties: talk2biomodels/cases/Case_3.md
      - Tutorials: 
        - ./notebooks/talk2biomodels/tutorial.ipynb
      - Agents:
          - T2B agent: talk2biomodels/agents/t2b_agent.md
      - States:
          - T2B state: talk2biomodels/states/state_talk2biomodels.md
      - Models:
          - System Bio Model: talk2biomodels/models/sys_bio_model.md
          - Basico Model: talk2biomodels/models/basico_model.md
      - Tools:
          - Search models: talk2biomodels/tools/search_models.md
          - Model information: talk2biomodels/tools/get_modelinfo.md
          - Simulate model: talk2biomodels/tools/simulate_model.md
          - Ask questions: talk2biomodels/tools/ask_question.md
          - Custom plots: talk2biomodels/tools/custom_plotter.md
          - Load biomodel: talk2biomodels/tools/load_biomodel.md

  - Talk2Cells:
      - Talk2Cells: talk2cells/intro.md
      - Agents:
          - SCP Agent: talk2cells/agents/scp_agent.md
      - States:
          - Talk2Cells: talk2cells/states/state_talk2cells.md
      - Tools:
          - Search studies: talk2cells/tools/search_studies.md
          - Display studies: talk2cells/tools/display_studies.md

  - Talk2KnowledgeGraphs:
      - Introduction: talk2knowledgegraphs/intro.md
      - Tutorials:
          - PrimeKG: ./notebooks/talk2knowledgegraphs/tutorial_primekg_loader.ipynb
          - StarkQA-PrimeKG: ./notebooks/talk2knowledgegraphs/tutorial_starkqa_primekg_loader.ipynb
          - BioBridge-PrimeKG: ./notebooks/talk2knowledgegraphs/tutorial_biobridge_primekg_loader.ipynb
          - PrimeKG Subgraph Extraction: ./notebooks/talk2knowledgegraphs/tutorial_primekg_subgraph.ipynb
          - Textual Embeddings (all-minilm): ./notebooks/talk2knowledgegraphs/tutorial_starkqa_primekg_textual_embeddings_all_minilm.ipynb
          - Textual Embeddings (nomic-embed-text): ./notebooks/talk2knowledgegraphs/tutorial_starkqa_primekg_textual_embeddings_nomic_embed_text.ipynb
          - Protein Embeddings: ./notebooks/talk2knowledgegraphs/tutorial_biobridge_primekg_protein_embeddings.ipynb
          - Embedding Alignment: ./notebooks/talk2knowledgegraphs/tutorial_multimodal_embeddings_alignment.ipynb
          - Evaluation (VSS): ./notebooks/talk2knowledgegraphs/tutorial_starkqa_primekg_evaluation_vss.ipynb
          - Talk2KG Agentic Tools: ./notebooks/talk2knowledgegraphs/tutorial_talk2kg_agentic_tools.ipynb 
      - Datasets:
          - Dataset: talk2knowledgegraphs/datasets/dataset.md
          - PrimeKG: talk2knowledgegraphs/datasets/primekg.md
          - StarkQA-PrimeKG: talk2knowledgegraphs/datasets/starkqa_primekg.md
          - BioBridge-PrimeKG: talk2knowledgegraphs/datasets/biobridge_primekg.md
      - Utils:
        - Embeddings:
          - Embeddings: talk2knowledgegraphs/utils/embeddings/embeddings.md
          - EmbeddingWithSentenceTransformer: talk2knowledgegraphs/utils/embeddings/sentence_transformer.md
          - EmbeddingWithHuggingFace: talk2knowledgegraphs/utils/embeddings/huggingface.md
          - EmbeddingWithOllama: talk2knowledgegraphs/utils/embeddings/ollama.md
        - Enrichments:
          - Enrichments: talk2knowledgegraphs/utils/enrichments/enrichments.md
          - EnrichmentWithOllama: talk2knowledgegraphs/utils/enrichments/ollama.md
      - Agents:
          - Talk2KG Agent: talk2knowledgegraphs/agents/t2kg_agent.md
      - States:
          - Talk2KG State: talk2knowledgegraphs/states/state_talk2knowledgegraphs.md
      - Tools:
          - Subgraph Extraction: talk2knowledgegraphs/tools/subgraph_extraction.md
          - Subgraph Summarization: talk2knowledgegraphs/tools/subgraph_summarization.md
          - GraphRAG Reasoning: talk2knowledgegraphs/tools/graphrag_reasoning.md
          - Load Arguments: talk2knowledgegraphs/tools/load_arguments.md

  - Talk2Scholars:
      - Introduction: talk2scholars/intro.md
      - Tutorials: ./notebooks/talk2scholars/tutorial.ipynb
      - Agents:
          - Main Agent: talk2scholars/agents/main_agent.md
          - S2 Agent: talk2scholars/agents/s2_agent.md
      - States:
          - Talk2Scholars state: talk2scholars/states/state_talk2scholars.md
      - Tools:
          - Search papers: talk2scholars/tools/search.md
          - Single paper recommendation: talk2scholars/tools/single_paper_rec.md
          - Multi paper recommendation: talk2scholars/tools/multi_paper_rec.md
          - Display results: talk2scholars/tools/display_results.md

  - Documentation:
      - Ops:
          - Introduction: ops/Documentation_intro.md
          - CodeOps: ops/CodeOps.md
          - DevOps: ops/DevOps.md
      - Contributing:
          - Contributing: CONTRIBUTING.md

repo_url: https://github.com/VirtualPatientEngine/AIAgents4Pharma
repo_name: VPE/AIAgents4Pharma

extra_css:
  - VPE.png
theme:
  name: material
  logo: assets/VPE.png
  palette:
  - accent: black
    primary: white
    scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  - accent: black
    primary: white
    scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
  features:
    - navigation.top
    - navigation.tabs
    - navigation.instant
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy
    - navigation.scrollable

plugins:
  - search:
      lang:
        - en
        - de
  - mkdocstrings:
      handlers:
        python:
          options:
            filters: None
  - mkdocs-jupyter:
      include_source: True
  - tags
  - include-markdown

markdown_extensions:
  - pymdownx.highlight
    # anchor_linenums: true
    # line_spans: __span
    # pygments_lang_class: true
  - pymdownx.superfences

extra:
  notebooks:
    - overview.md: notebooks/overview.md
