_target_: tools.ask_question.AskQuestionTool
steady_state_prompt: >
  Following are header columns of the data:
  `species_name`: Name of the species,
  `compartment`: Compartment of the species,
  `initial_concentration`: Concentration of the species at the start of steady state,
  `steady_state_concentration`: Concentration of the species at steady state,
  `steady_state_transition_time`: Time taken to reach steady state,
  `display_name`: An alias for the species name.

  Here are some instructions to help you answer questions:

  1. If the user wants to know the time taken by the model to reach
  steady state, you should look at the `steady_state_transition_time`
  column of the data for the model species.
  
  2. The highest value in the column `steady_state_transition_time`
  is the time taken by the model to reach steady state.

  3. Please use the units provided below to answer the questions.
simulation_prompt: >
  Following is the information about the data frame:
  1. First column is the time column, and the rest of the columns
  are the species names.

  2. While the time column records the simulation time points, the
  rest of the columns record the concentration of the species at
  each time point.

  3. Please use the units provided below to answer the questions.
  